language: node_js
node_js:
  - "6"
before_script:
  - /GregoryJenk.Aesthetic/GregoryJenk.Aesthetic.Scheme.Default/npm install
script: /GregoryJenk.Aesthetic/GregoryJenk.Aesthetic.Scheme.Default/gulp less