name: Continuous Integration
on:
    push:
        branches:
            - "**"
        tags-ignore:
            - "**"
    pull_request:
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup (.NET)
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 9.0.x
            - name: Restore (.NET)
              run: dotnet restore src
            - name: Build (.NET)
              run: dotnet build src --configuration Release --no-restore